version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 150583
      POSTGRES_DB: warehouse
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
